name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  palette_generator: ^0.3.3
  http: ^0.13.3
  english_words: ^4.0.0
  provider: ^6.0.0
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.6.18+3
  search_page: ^2.3.0
  font_awesome_flutter: ^10.6.0
  basic_utils: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_native_splash:
  clor: "#ffffff"
  image: assets/img/Logo.png
  android: true